groups:
  - name: node_health_alerts
    rules:
      - alert: NodeUnhealthy
        expr: node_health == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Node health check failed"
          description: "Node {{ $labels.instance }} has failed health checks"

      - alert: HighMemoryUsage
        expr: memory_usage_percent > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighCPUUsage
        expr: cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighDiskUsage
        expr: disk_usage_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is {{ $value }}% on {{ $labels.instance }}"
